### ISSUE TITLE
"cd\" is not working in Windows

### ISSUE THREAD

**Issue by cithukyaw** [johnhidey/hdy.brackets-shell#43]
This may be a bug when developer wants to change the directory out of the current open project.

**Expected:**
When executes `cd\` in the current directory, change to the drive.

**Actual:**
When executes `cd\` in the current directory, nothing was changed.

![brackets-shell-backward-slash](https://cloud.githubusercontent.com/assets/4285555/5676008/50cbdbac-97fb-11e4-81c1-f5b83ff9f349.png)

**Versions**
0.0.12
Windows 7

**Comment by johnhidey** [comment]
This is not a bug.  I made the decision to separate the command from the arguments for CD.  If you execute `CD \` instead of `CD\` it should work as expected, it not please let me know.  The reason I did this is that no over OS supports this with their implementation of CD.  Thanks.  Hope you are finding the extension useful.  Some good enhancements coming soon.

**Comment by cithukyaw** [comment]
> If you execute CD \ instead of CD\ it should work as expected

It did work except a warning. Thanks!

    '\\'
    CMD does not support UNC paths as current directories.

**Comment by johnhidey** [comment]
I'll look into that warning. Just saw that myself also

Sent from my Windows Phone
________________________________
